### PR TITLE
Gh92 media ingest

### LINKED ISSUE #92: Handle ingest of media files when importing media procedures
According to the [Media Service RESTful API](https://collectionspace.atlassian.net/wiki/spaces/DOC/pages/1545308896/Media+Service+RESTful+API) and [Blob Service RESTful API](https://collectionspace.atlassian.net/wiki/spaces/CSPACE50/pages/665882831/Blob+Service+RESTful+API#BlobServiceRESTfulAPI-post_blobUri) documentation, it appears that...

- It is not currently possible to batch add more than one media file/blob to a given Media Handling record
- You can add a blob to a Media Handling record that already has a blob via an update request, but "any existing association that the media record had with another blob will be lost"

This is potentially destructive, which is probably why the old "converter tool" only supported blob ingest for records transferred as new, not updates. 

It seems useful to be able to update, though. Sketching out what would need to happen to make that possible:

* Non-media handling mapper
  * nothing/irrelevant 
* Media handling mapper
  * Check each row of CSV for `mediaFileURI` value
    * Not present or present but unpopulated -> do nothing
    * Present/populated
      * New record
        * Processing step -> cache blob uri value with mapped record data
        * Transfer step -> include blob ingest query parameter in call
      * Existing record
        * Processing step -> Query existing services-base/media/CSID/blob URI. 
          * If query is successful -> (1) emit a warning that there is an existing media blob and we will not be replacing it. (2) Do not cache blob URI value.
          * If query returns `get failed on org.collectionspace.services.media.MediaResource csid=null` => cache the blobURI value
        * Transfer step -> If the blob URI is cached with the XML record data, include the blob ingest query parameter in call. 

Here is how the old converter tool handled this in [the transfer (i.e. new record creation) process](https://github.com/collectionspace/cspace-converter/blob/5938729303aa42df7926116ab628cc0f1079c54f/app/services/remote_action_service.rb#L87):

```
        blob_uri = object.data_object.csv_data.fetch('bloburi', nil)
        blob_uri = URI.encode blob_uri if !blob_uri.blank?
        params   = (blob_uri && object.type == 'Media') ? { query: { 'blobUri' => blob_uri } } : {}
        response = client.post(service[:path], object.content, params)
```

### PR DESCRIPTION
**Pull request by kspurgin**
Closes #92

### CODE REVIEW

**Comment by kspurgin** [comment]
@mark-cooper - This is waiting on merge of collectionspace/collectionspace-client#12 but in the meantime, what are your thoughts on testing media ingest in this application?

I verified that any errors that collectionspace-client throws regarding being unable to download or otherwise ingest a file get captured and recorded as errors in the batch spreadsheet. 

Really not sure how to fake all that up for testing here, or if it's important to do so? Feelings on the matter?

**Comment by mark-cooper** [comment]
@kspurgin there are a couple of conflicts here after merging everything else. I can reconcile them if you like (thought I'd ask before stomping over or replacing your branch). The service looks like its from one of your other PRs. The test is from me: to resolve you can rebase then remove the `with_caching` blocks because the tests have access to redis now.

**Comment by kspurgin** [comment]
@mark-cooper - conflicts have been addressed.

When I tried to run the tests, I got: 
 
```
WARNING:
The Stimulus Reflex javascript package version (3.3.0-pre2) does not match the Rubygem version (3.4.1).
To update the Stimulus Reflex npm package:
    yarn upgrade stimulus_reflex@3.4.1
```

Upgrading this changed the yarn.lock and package.json files:

```
❯  git diff
diff --git a/package.json b/package.json
index c45f5ec..7899f76 100644
--- a/package.json
+++ b/package.json
@@ -13,7 +13,7 @@
     "local-time": "^2.1.0",
     "node-sass": "^5.0.0",
     "stimulus": "^1.1.1",
-    "stimulus_reflex": "^3.3.0-pre2",
+    "stimulus_reflex": "3.4.1",
     "turbolinks": "^5.2.0"
   },
   "version": "0.1.0",
diff --git a/yarn.lock b/yarn.lock
index 2bda8f1..36c9e90 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -7003,7 +7003,7 @@ stimulus@^1.1.1:
     "@stimulus/core" "^1.1.1"
     "@stimulus/webpack-helpers" "^1.1.1"

-stimulus_reflex@^3.3.0-pre2:
+stimulus_reflex@3.4.1:
   version "3.4.1"
   resolved "https://registry.yarnpkg.com/stimulus_reflex/-/stimulus_reflex-3.4.1.tgz#2606aee3b2911b5939d68f65a75262fe3c626204"
   integrity sha512-YbFcuE4HndNe9RBQvF/Vu+7GDt0zLGdhQTXuGfLDVti1qggPG3kPgV1YBZ9volzBTGUmLp2PQbxG9j5AIyYp5A==
```

I am seeing [the Gemfile requiring ~> 3.4](https://github.com/collectionspace/collectionspace-csv-importer/blob/c8dd474485a3315019c250468167ec1b731adbf0/Gemfile#L41), so should I commit these?

**Comment by mark-cooper** [comment]
@kspurgin yeah that diff looks good. Include it then this can be merged 👍

**Comment by kspurgin** [comment]
@mark-cooper changes from that diff are pushed. Ready to go.

**Pull request merged**
