### PR TITLE
Fix preprocessing hanging when `collectionspace-client` does not support record type

### LINKED ISSUE #75: Importer hanging in Bot Garden > Propagations preprocessing setp
I haven't tried other procedures so not sure if the CSV is the issue, my connection, etc. Will do more investigating just wanted to get this sketched out.

Tried two Bot Garden Propagation imports, both hanging in preprocessing. CSV files attached.

[Propagation Sample Data for QA.csv](https://github.com/collectionspace/collectionspace-csv-importer/files/6688518/Propagation.Sample.Data.for.QA.csv)

[5f5f1c69-fe4a-44b4-95c3-4999653e1611.csv](https://github.com/collectionspace/collectionspace-csv-importer/files/6688517/5f5f1c69-fe4a-44b4-95c3-4999653e1611.csv)

### PR DESCRIPTION
**Pull request by kspurgin**
Fixes #75 

There is a failing test here that looks to be unrelated to changes I made (?) as I did not mess with the fixtures or how mappers get downloaded at all.

### CODE REVIEW

**Comment by mark-cooper** [comment]
@kspurgin I haven't looked into the cause but if I checkout this branch, `bundle` and bootstrap I'm getting:

```
Using default DB PostgreSQL port 5432
Error response from daemon: No such container: postgres
Error response from daemon: No such container: redis
ac60faa7e77b6496942227d6c1da78e5fe18a231de5f89fc011c04b34eca7ccd
33cb3220dd3a865dab6c776593da0ce425f737f084fa183b5a9f58495c8a4074
Dev cache is already enabled.
/home/mcooper/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `block in load_missing_constant': uninitialized constant CollectionSpace::Mapper::DataPrepper (NameError)
...
```

I can take a more detailed look later, but thought I'd bounce it to you for now.

**Comment by kspurgin** [comment]
@mark-cooper - Hmm, I'm not able to reproduce that. 

```
~/code/cspace-batch-import ( master {1} ✓ )
❯  git checkout gh-iss-75
Switched to branch 'gh-iss-75'
Your branch is up to date with 'origin/gh-iss-75'.

~/code/cspace-batch-import ( gh-iss-75 {1} ✓ )
❯  bundle
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
[...lots o' gems...]
Using json 2.3.1
Using collectionspace-client 0.7.0 from https://github.com/collectionspace/collectionspace-client.git (at v0.7.0@4759c1a)
Using facets 3.1.0
Using xxhash 0.4.0
Using collectionspace-mapper 2.4.4 from https://github.com/collectionspace/collectionspace-mapper.git (at v2.4.4@5eb9c10)
Using redis 4.2.5
Using zache 0.12.0
Using collectionspace-refcache 0.7.3 from https://github.com/collectionspace/collectionspace-refcache.git (at v0.7.3@1744d98)
[...lots o' gems...]
Bundle complete! 44 Gemfile dependencies, 149 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

~/code/cspace-batch-import ( gh-iss-75 {1} ✓ )
❯  ./bootstrap.sh
Using default DB PostgreSQL port 5432
postgres
postgres
redis
redis
5634a64b64e2243c004c6e9624cde52c36df6416974fef031fa4d411ccacd49d
bd57dc3b36fa43b5325699fba52f37eae778444484566552498c4c8ef4ec99c8
Dev cache is already enabled.
Running via Spring preloader in process 37491
Created database 'importer_development'
Created database 'importer_test'
```

**Comment by kspurgin** [comment]
Is bootsnap on your machine somehow using an older cached version of collectionspace-mapper, perhaps?

**Comment by kspurgin** [comment]
The test failure I am getting is: 

```
Error:
Step::PreprocessesControllerTest#test_should_create_a_preprocess:
Module::DelegationError: download delegated to attachment, but attachment is nil
    app/models/batch.rb:104:in `block in fetch_mapper'
    app/models/batch.rb:103:in `fetch_mapper'
    app/models/batch.rb:49:in `handler'
    app/jobs/preprocess_job.rb:18:in `perform'
    test/controllers/step/preprocesses_controller_test.rb:32:in `block in <class:PreprocessesControllerTest>'


rails test test/controllers/step/preprocesses_controller_test.rb:25
```

**Comment by mark-cooper** [comment]
@kspurgin don't think so. I also get this error if I try to use the mapper directly, so there may be a system dependent load order issue (speculating, are you on Mac OS?):

```
[mcooper:~/Projects/collectionspace/collectionspace-mapper] tag: v2.4.4(+1/-1) 3s ± ./bin/console
Traceback (most recent call last):
        10: from ./bin/console:4:in `<main>'
         9: from ./bin/console:4:in `require'
         8: from /home/mcooper/Projects/collectionspace/collectionspace-mapper/lib/collectionspace/mapper.rb:15:in `<top (required)>'
         7: from /home/mcooper/Projects/collectionspace/collectionspace-mapper/lib/collectionspace/mapper.rb:17:in `<module:CollectionSpace>'
         6: from /home/mcooper/Projects/collectionspace/collectionspace-mapper/lib/collectionspace/mapper.rb:29:in `<module:Mapper>'
         5: from /home/mcooper/Projects/collectionspace/collectionspace-mapper/lib/collectionspace/mapper.rb:29:in `each'
         4: from /home/mcooper/Projects/collectionspace/collectionspace-mapper/lib/collectionspace/mapper.rb:30:in `block in <module:Mapper>'
         3: from /home/mcooper/Projects/collectionspace/collectionspace-mapper/lib/collectionspace/mapper.rb:30:in `require'
         2: from /home/mcooper/Projects/collectionspace/collectionspace-mapper/lib/collectionspace/mapper/authority_hierarchy_prepper.rb:3:in `<top (required)>'
         1: from /home/mcooper/Projects/collectionspace/collectionspace-mapper/lib/collectionspace/mapper/authority_hierarchy_prepper.rb:4:in `<module:CollectionSpace>'
/home/mcooper/Projects/collectionspace/collectionspace-mapper/lib/collectionspace/mapper/authority_hierarchy_prepper.rb:5:in `<module:Mapper>': uninitialized constant CollectionSpace::Mapper::DataPrepper (NameError)
```

**Comment by mark-cooper** [comment]
Wheeling back to this, adding:

```ruby
require_relative 'data_prepper'
require_relative 'term_searchable'

module CollectionSpace
  module Mapper
    class AuthorityHierarchyPrepper < CollectionSpace::Mapper::DataPrepper
# ... and on
```

To `authority_hierarchy_prepper.rb` gets me to the console.

**Comment by kspurgin** [comment]
Now also fixes #78

**Comment by kspurgin** [comment]
@mark-cooper The commit I just made should fix that load order issue. It also bumps all the versions of all the things. 

Still seeing the preprocess job test fail. I spent probably too much time last evening trying to figure out how to set up fixtures or stubs or something to make that test happy, and didn't figure it out. 

The `fetch_mapper` method in `models/batch` does `Rails.cache.fetch` to get the mapper if it's there, and if it isn't it re-downloads the mapper. 

But in the test environment, NullCache is being used and it doesn't want to allow http requests.

**Comment by mark-cooper** [comment]
@kspurgin I attached a file to the mapper for the test. Everything else LGTM 👍

**Comment by kspurgin** [comment]
@mark-cooper - Are you not getting this error? : 

```
Error:
PreprocessJobTest#test_finishes_the_job:
Module::DelegationError: download delegated to attachment, but attachment is nil
    app/models/batch.rb:104:in `block in fetch_mapper'
    app/models/batch.rb:103:in `fetch_mapper'
    app/models/batch.rb:49:in `handler'
    app/jobs/preprocess_job.rb:18:in `perform'
    test/jobs/preprocess_job_test.rb:29:in `block in <class:PreprocessJobTest>'


rails test test/jobs/preprocess_job_test.rb:21

................................................................................................................................E

Error:
Step::PreprocessesControllerTest#test_should_create_a_preprocess:
Module::DelegationError: download delegated to attachment, but attachment is nil
    app/models/batch.rb:104:in `block in fetch_mapper'
    app/models/batch.rb:103:in `fetch_mapper'
    app/models/batch.rb:49:in `handler'
    app/jobs/preprocess_job.rb:18:in `perform'
    test/controllers/step/preprocesses_controller_test.rb:37:in `block in <class:PreprocessesControllerTest>'


rails test test/controllers/step/preprocesses_controller_test.rb:30
```
Now that you fixed the test failure you were seeing, I am getting this twice instead of once!

**Comment by mark-cooper** [comment]
@kspurgin nope:

```
Running via Spring preloader in process 27686
Run options: --seed 56366

# Running:

................................................................................................................/home/mcooper/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/csvlint-0.4.0/lib/csvlint/validate.rb:437: warning: URI.escape is obsolete
.../home/mcooper/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/csvlint-0.4.0/lib/csvlint/validate.rb:437: warning: URI.escape is obsolete
../home/mcooper/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/csvlint-0.4.0/lib/csvlint/validate.rb:437: warning: URI.escape is obsolete
.../home/mcooper/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/csvlint-0.4.0/lib/csvlint/validate.rb:437: warning: URI.escape is obsolete
...........................................................................................................................................................................................................................

Finished in 4.424038s, 76.6268 runs/s, 136.9789 assertions/s.
339 runs, 606 assertions, 0 failures, 0 errors, 0 skips
```

On Ubuntu and Mac. Master -- and retried after fresh bundle, yarn and bootstrap, all checks out.

Seeing it twice suggests you get something weird going on. Maybe try `spring stop` and / or clearing the tmp folder and kick it again?

**Comment by mark-cooper** [comment]
@kspurgin I see it in the context of https://github.com/collectionspace/collectionspace-csv-importer/pull/88 -- I'll look into it there.

**Pull request merged**
